const price = [
  { Country1: "Hong Kong and China", Country2: "China", "charge/kg": "$3.93" },
  {
    Country1: "Hong Kong and China",
    Country2: "Hong Kong",
    "charge/kg": "$3.93",
  },
  {
    Country1: "Hong Kong and China",
    Country2: "Rest of Asia",
    "charge/kg": "$3.93",
  },
  {
    Country1: "Hong Kong and China",
    Country2: "South Asia",
    "charge/kg": "$3.93",
  },
  { Country1: "Hong Kong and China", Country2: "Europe", "charge/kg": "$0.87" },
  {
    Country1: "Hong Kong and China",
    Country2: "Americas",
    "charge/kg": "$0.87",
  },
  {
    Country1: "Hong Kong and China",
    Country2: "Rest of World",
    "charge/kg": "$0.87",
  },
  {
    Country1: "Australia and NewZealand",
    Country2: "China",
    "charge/kg": "$10.93",
  },
  {
    Country1: "Australia and NewZealand",
    Country2: "Hong Kong",
    "charge/kg": "$10.93",
  },
  {
    Country1: "Australia and NewZealand",
    Country2: "Rest of Asia",
    "charge/kg": "$10.93",
  },
  {
    Country1: "Australia and NewZealand",
    Country2: "South Asia",
    "charge/kg": "$10.93",
  },
  {
    Country1: "Australia and NewZealand",
    Country2: "Europe",
    "charge/kg": "$8.74",
  },
  {
    Country1: "Australia and NewZealand",
    Country2: "Americas",
    "charge/kg": "$8.74",
  },
  {
    Country1: "Australia and NewZealand",
    Country2: "Rest of World",
    "charge/kg": "$8.74",
  },
  { Country1: "Rest of Asia ", Country2: "China", "charge/kg": "$3.93" },
  { Country1: "Rest of Asia ", Country2: "Hong Kong", "charge/kg": "$3.93" },
  { Country1: "Rest of Asia ", Country2: "Rest of Asia", "charge/kg": "$3.93" },
  { Country1: "Rest of Asia ", Country2: "South Asia", "charge/kg": "$3.93" },
  { Country1: "Rest of Asia ", Country2: "Europe", "charge/kg": "$0.87" },
  { Country1: "Rest of Asia ", Country2: "Americas", "charge/kg": "$0.87" },
  {
    Country1: "Rest of Asia ",
    Country2: "Rest of World",
    "charge/kg": "$0.87",
  },
  { Country1: "Europe", Country2: "China", "charge/kg": "$6.56" },
  { Country1: "Europe", Country2: "Hong Kong", "charge/kg": "$6.56" },
  { Country1: "Europe", Country2: "Rest of Asia", "charge/kg": "$5.46" },
  { Country1: "Europe", Country2: "South Asia", "charge/kg": "$3.93" },
  { Country1: "Europe", Country2: "Europe", "charge/kg": "$0.87" },
  { Country1: "Europe", Country2: "Americas", "charge/kg": "$0.87" },
  { Country1: "Europe", Country2: "Rest of World", "charge/kg": "$0.87" },
  { Country1: "Americas", Country2: "China", "charge/kg": "$10.93" },
  { Country1: "Americas", Country2: "Hong Kong", "charge/kg": "$10.93" },
  { Country1: "Americas", Country2: "Rest of Asia", "charge/kg": "$5.46" },
  { Country1: "Americas", Country2: "South Asia", "charge/kg": "$3.93" },
  { Country1: "Americas", Country2: "Europe", "charge/kg": "$1.31" },
  { Country1: "Americas", Country2: "Americas", "charge/kg": "$0.87" },
  { Country1: "Americas", Country2: "Rest of World", "charge/kg": "$0.87" },
  { Country1: "Rest of World", Country2: "China", "charge/kg": "$6.56" },
  { Country1: "Rest of World", Country2: "Hong Kong", "charge/kg": "$6.56" },
  { Country1: "Rest of World", Country2: "Rest of Asia", "charge/kg": "$5.46" },
  { Country1: "Rest of World", Country2: "South Asia", "charge/kg": "$3.93" },
  { Country1: "Rest of World", Country2: "Europe", "charge/kg": "$0.87" },
  { Country1: "Rest of World", Country2: "Americas", "charge/kg": "$0.87" },
  {
    Country1: "Rest of World",
    Country2: "Rest of World",
    "charge/kg": "$0.87",
  },
];

const europe = [
  "United Kingdom",
  "France",
  "Germany",
  "Spain",
  "Italy",
  "Russia",
  "Greece",
  "Sweden",
  "Norway",
  "Portugal",
];

const americas = [
  "United States",
  "Mexico",
  "Canada",
  "Jamaica",
  "Costa Rica",
  "Guatemala",
  "Honduras",
  "El Salvador",
  "Nicaragua",
  "Panama",
  "Belize",
  "Brazil",
  "Argentina",
  "Colombia",
  "Peru",
  "Chile",
  "Venezuel",
];
const asian = [
  "Afghanistan",
  "Armenia",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Bhutan",
  "Brunei",
  "Cambodia",
  "China",
  "Cyprus",
  "Georgia",
  "Hong Kong",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Israel",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Lebanon",
  "Malaysia",
  "Maldives",
  "Mongolia",
  "Myanmar",
  "Nepal",
  "North Korea",
  "Oman",
  "Pakistan",
  "Palestine",
  "Philippines",
  "Qatar",
  "Saudi Arabia",
  "Singapore",
  "South Korea",
  "Sri Lanka",
  "Syria",
  "Tajikistan",
  "Thailand",
  "Timor-Leste",
  "Turkey",
  "Turkmenistan",
  "United Arab Emirates",
  "Uzbekistan",
  "Vietnam",
  "Yemen",
];
